services:
  build-time-sender-test:
    build:
      context: .
      args:
        BUILD_TIME: ${BUILD_TIME:-unknown01}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    restart: unless-stopped
